# Module 1: Data validation and pre-processing technique

In [1]:
#import library packages
import pandas as pd
import numpy as np

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
#Load given dataset
data = pd.read_csv("Lung Cancer.csv")

Before drop the given dataset

In [4]:
data.head()

GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
0      M   69        1               2        2              1   
1      M   74        2               1        1              1   
2      F   59        1               1        1              2   
3      M   63        2               2        2              1   
4      F   63        1               2        1              1   

   CHRONIC_DISEASE  FATIGUE   ALLERGY   WHEEZING  ALCOHOL_CONSUMING  COUGHING  \
0                1         2         1         2                  2         2   
1                2         2         2         1                  1         1   
2                1         2         1         2                  1         2   
3                1         1         1         1                  2         1   
4                1         1         1         2                  1         2   

   SHORTNESS_OF_BREATH  SWALLOWING_DIFFICULTY  CHEST_PAIN LUNG_CANCER  
0                    2                      2           2         YES  
1                    2                      2           2         YES  
2                    2                      1           2          NO  
3                    1                      2           2          NO  
4                    2                      1           1          NO

In [5]:
#shape
data.shape

(540, 16)

After drop the given dataset

In [6]:
df = data.dropna()

In [7]:
df.head()

GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
0      M   69        1               2        2              1   
1      M   74        2               1        1              1   
2      F   59        1               1        1              2   
3      M   63        2               2        2              1   
4      F   63        1               2        1              1   

   CHRONIC_DISEASE  FATIGUE   ALLERGY   WHEEZING  ALCOHOL_CONSUMING  COUGHING  \
0                1         2         1         2                  2         2   
1                2         2         2         1                  1         1   
2                1         2         1         2                  1         2   
3                1         1         1         1                  2         1   
4                1         1         1         2                  1         2   

   SHORTNESS_OF_BREATH  SWALLOWING_DIFFICULTY  CHEST_PAIN LUNG_CANCER  
0                    2                      2           2         YES  
1                    2                      2           2         YES  
2                    2                      1           2          NO  
3                    1                      2           2          NO  
4                    2                      1           1          NO

In [8]:
df.shape

(540, 16)

In [9]:
#show columns
df.columns

Index(['GENDER', 'AGE', 'SMOKING', 'YELLOW_FINGERS', 'ANXIETY',
       'PEER_PRESSURE', 'CHRONIC_DISEASE', 'FATIGUE ', 'ALLERGY ', 'WHEEZING',
       'ALCOHOL_CONSUMING', 'COUGHING', 'SHORTNESS_OF_BREATH',
       'SWALLOWING_DIFFICULTY', 'CHEST_PAIN', 'LUNG_CANCER'],
      dtype='object')

In [10]:
#To describe the dataframe
df.describe()

AGE     SMOKING  YELLOW_FINGERS     ANXIETY  PEER_PRESSURE  \
count  540.000000  540.000000      540.000000  540.000000     540.000000   
mean    61.824074    1.516667        1.444444    1.398148       1.392593   
std      9.603096    0.500185        0.497365    0.489970       0.488780   
min     21.000000    1.000000        1.000000    1.000000       1.000000   
25%     57.000000    1.000000        1.000000    1.000000       1.000000   
50%     62.000000    2.000000        1.000000    1.000000       1.000000   
75%     68.000000    2.000000        2.000000    2.000000       2.000000   
max     87.000000    2.000000        2.000000    2.000000       2.000000   

       CHRONIC_DISEASE    FATIGUE     ALLERGY     WHEEZING  ALCOHOL_CONSUMING  \
count       540.000000  540.000000  540.000000  540.000000         540.000000   
mean          1.466667    1.607407    1.366667    1.394444           1.385185   
std           0.499350    0.488780    0.482341    0.489184           0.487090   
min           1.000000    1.000000    1.000000    1.000000           1.000000   
25%           1.000000    1.000000    1.000000    1.000000           1.000000   
50%           1.000000    2.000000    1.000000    1.000000           1.000000   
75%           2.000000    2.000000    2.000000    2.000000           2.000000   
max           2.000000    2.000000    2.000000    2.000000           2.000000   

         COUGHING  SHORTNESS_OF_BREATH  SWALLOWING_DIFFICULTY  CHEST_PAIN  
count  540.000000           540.000000             540.000000  540.000000  
mean     1.425926             1.646296               1.311111    1.418519  
std      0.494941             0.478562               0.463377    0.493774  
min      1.000000             1.000000               1.000000    1.000000  
25%      1.000000             1.000000               1.000000    1.000000  
50%      1.000000             2.000000               1.000000    1.000000  
75%      2.000000             2.000000               2.000000    2.000000  
max      2.000000             2.000000               2.000000    2.000000

In [11]:
#Checking datatype and information about dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 540 entries, 0 to 539
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype 
---  ------                 --------------  ----- 
 0   GENDER                 540 non-null    object
 1   AGE                    540 non-null    int64 
 2   SMOKING                540 non-null    int64 
 3   YELLOW_FINGERS         540 non-null    int64 
 4   ANXIETY                540 non-null    int64 
 5   PEER_PRESSURE          540 non-null    int64 
 6   CHRONIC_DISEASE        540 non-null    int64 
 7   FATIGUE                540 non-null    int64 
 8   ALLERGY                540 non-null    int64 
 9   WHEEZING               540 non-null    int64 
 10  ALCOHOL_CONSUMING      540 non-null    int64 
 11  COUGHING               540 non-null    int64 
 12  SHORTNESS_OF_BREATH    540 non-null    int64 
 13  SWALLOWING_DIFFICULTY  540 non-null    int64 
 14  CHEST_PAIN             540 non-null    int64 
 15  LUNG_CANCER            

In [12]:
#Checking sum of missing values
df.isnull().sum()

GENDER                   0
AGE                      0
SMOKING                  0
YELLOW_FINGERS           0
ANXIETY                  0
PEER_PRESSURE            0
CHRONIC_DISEASE          0
FATIGUE                  0
ALLERGY                  0
WHEEZING                 0
ALCOHOL_CONSUMING        0
COUGHING                 0
SHORTNESS_OF_BREATH      0
SWALLOWING_DIFFICULTY    0
CHEST_PAIN               0
LUNG_CANCER              0
dtype: int64

In [13]:
df.GENDER.unique()

array(['M', 'F'], dtype=object)

In [14]:
df.AGE.unique()

array([69, 74, 59, 63, 75, 52, 51, 68, 53, 61, 72, 60, 58, 48, 57, 44, 64,
       21, 65, 55, 62, 56, 67, 77, 70, 54, 49, 73, 47, 71, 66, 76, 78, 81,
       79, 38, 39, 87, 46], dtype=int64)

In [15]:
df.YELLOW_FINGERS.unique()

array([2, 1], dtype=int64)

In [16]:
df.CHRONIC_DISEASE.unique()

array([1, 2], dtype=int64)

In [17]:
df.ALCOHOL_CONSUMING.unique()

array([2, 1], dtype=int64)

In [18]:
df.COUGHING.unique()

array([2, 1], dtype=int64)

In [19]:
df.SHORTNESS_OF_BREATH.unique()

array([2, 1], dtype=int64)

In [20]:
df.CHEST_PAIN.unique()

array([2, 1], dtype=int64)

In [21]:
print("Minimum value of Age of patient is:", df.AGE.min())
print("Maximum value of Age of patient is:", df.AGE.max())

Minimum value of Age of patient is: 21
Maximum value of Age of patient is: 87


In [22]:
print("Age of patient ranges :", sorted(df['AGE'].unique()))

Age of patient ranges : [21, 38, 39, 44, 46, 47, 48, 49, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 81, 87]


In [23]:
df.corr()

AGE   SMOKING  YELLOW_FINGERS   ANXIETY  \
AGE                    1.000000 -0.120092       -0.030989  0.024377   
SMOKING               -0.120092  1.000000        0.014915  0.052361   
YELLOW_FINGERS        -0.030989  0.014915        1.000000  0.490628   
ANXIETY                0.024377  0.052361        0.490628  1.000000   
PEER_PRESSURE          0.073636 -0.026813        0.189097  0.244745   
CHRONIC_DISEASE       -0.018442 -0.194615       -0.104583 -0.010111   
FATIGUE                0.022808 -0.011130       -0.250151 -0.236998   
ALLERGY               -0.092992  0.159183       -0.007734 -0.045794   
WHEEZING               0.090627 -0.114115        0.101672 -0.106862   
ALCOHOL_CONSUMING      0.100187 -0.026399       -0.079986  0.118046   
COUGHING               0.153586 -0.081187        0.186743 -0.073246   
SHORTNESS_OF_BREATH   -0.011143  0.020798       -0.148965 -0.355688   
SWALLOWING_DIFFICULTY -0.005605  0.049629        0.429339  0.507547   
CHEST_PAIN            -0.002051  0.151992        0.079742  0.000142   

                       PEER_PRESSURE  CHRONIC_DISEASE  FATIGUE   ALLERGY   \
AGE                         0.073636        -0.018442  0.022808 -0.092992   
SMOKING                    -0.026813        -0.194615 -0.011130  0.159183   
YELLOW_FINGERS              0.189097        -0.104583 -0.250151 -0.007734   
ANXIETY                     0.244745        -0.010111 -0.236998 -0.045794   
PEER_PRESSURE               1.000000         0.053716 -0.044811  0.017837   
CHRONIC_DISEASE             0.053716         1.000000  0.060304  0.120165   
FATIGUE                    -0.044811         0.060304  1.000000  0.108074   
ALLERGY                     0.017837         0.120165  0.108074  1.000000   
WHEEZING                    0.080525        -0.094179  0.097940  0.305868   
ALCOHOL_CONSUMING           0.111753         0.091025 -0.166302  0.424318   
COUGHING                    0.074419        -0.227705  0.017611  0.292725   
SHORTNESS_OF_BREATH        -0.253928         0.024326  0.491875 -0.015807   
SWALLOWING_DIFFICULTY       0.287066         0.036883 -0.115045  0.119532   
CHEST_PAIN                  0.109728        -0.131428 -0.032856  0.343792   

                       WHEEZING  ALCOHOL_CONSUMING  COUGHING  \
AGE                    0.090627           0.100187  0.153586   
SMOKING               -0.114115          -0.026399 -0.081187   
YELLOW_FINGERS         0.101672          -0.079986  0.186743   
ANXIETY               -0.106862           0.118046 -0.073246   
PEER_PRESSURE          0.080525           0.111753  0.074419   
CHRONIC_DISEASE       -0.094179           0.091025 -0.227705   
FATIGUE                0.097940          -0.166302  0.017611   
ALLERGY                0.305868           0.424318  0.292725   
WHEEZING               1.000000           0.350036  0.530859   
ALCOHOL_CONSUMING      0.350036           1.000000  0.287876   
COUGHING               0.530859           0.287876  1.000000   
SHORTNESS_OF_BREATH    0.066086          -0.274029  0.151580   
SWALLOWING_DIFFICULTY  0.194251           0.150333  0.003595   
CHEST_PAIN             0.298445           0.346726  0.195412   

                       SHORTNESS_OF_BREATH  SWALLOWING_DIFFICULTY  CHEST_PAIN  
AGE                              -0.011143              -0.005605   -0.002051  
SMOKING                           0.020798               0.049629    0.151992  
YELLOW_FINGERS                   -0.148965               0.429339    0.079742  
ANXIETY                          -0.355688               0.507547    0.000142  
PEER_PRESSURE                    -0.253928               0.287066    0.109728  
CHRONIC_DISEASE                   0.024326               0.036883   -0.131428  
FATIGUE                           0.491875              -0.115045   -0.032856  
ALLERGY                          -0.015807               0.119532    0.343792  
WHEEZING                          0.066086               0.194251    0.298445  
ALCOHOL_CONSUMING                -0.274029   

Before Pre-Processing

In [24]:
df.head()

GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
0      M   69        1               2        2              1   
1      M   74        2               1        1              1   
2      F   59        1               1        1              2   
3      M   63        2               2        2              1   
4      F   63        1               2        1              1   

   CHRONIC_DISEASE  FATIGUE   ALLERGY   WHEEZING  ALCOHOL_CONSUMING  COUGHING  \
0                1         2         1         2                  2         2   
1                2         2         2         1                  1         1   
2                1         2         1         2                  1         2   
3                1         1         1         1                  2         1   
4                1         1         1         2                  1         2   

   SHORTNESS_OF_BREATH  SWALLOWING_DIFFICULTY  CHEST_PAIN LUNG_CANCER  
0                    2                      2           2         YES  
1                    2                      2           2         YES  
2                    2                      1           2          NO  
3                    1                      2           2          NO  
4                    2                      1           1          NO

After Pre-Processing

In [25]:
from sklearn.preprocessing import LabelEncoder
var_mod = ['GENDER','LUNG_CANCER']
le = LabelEncoder()
for i in var_mod:
    df[i] = le.fit_transform(df[i]).astype(int)

In [26]:
df.head()

GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
0       1   69        1               2        2              1   
1       1   74        2               1        1              1   
2       0   59        1               1        1              2   
3       1   63        2               2        2              1   
4       0   63        1               2        1              1   

   CHRONIC_DISEASE  FATIGUE   ALLERGY   WHEEZING  ALCOHOL_CONSUMING  COUGHING  \
0                1         2         1         2                  2         2   
1                2         2         2         1                  1         1   
2                1         2         1         2                  1         2   
3                1         1         1         1                  2         1   
4                1         1         1         2                  1         2   

   SHORTNESS_OF_BREATH  SWALLOWING_DIFFICULTY  CHEST_PAIN  LUNG_CANCER  
0                    2                      2           2            1  
1                    2                      2           2            1  
2                    2                      1           2            0  
3                    1                      2           2            0  
4                    2                      1           1            0